### ISSUE TITLE
Feature: Add `Button` to component

### ISSUE THREAD

**Issue by babblebey** [abeg-help/frontend#107]
## Issue Type

- [ ] Bug Report
- [x] Feature Request
- [x] Enhancement
- [ ] Other (Please specify)

## Description

We are planning to introduce a new `Button` component to our project, and to ensure its versatility, we'd like to implement it using `forwardRef`. This component should be added to the file `components/primitives/Button/button.tsx`.

**Specifications:**

The `Button` component should meet the following specifications:

- **Variants**: It should support multiple button variants, including primary, secondary, and danger buttons.
- **Sizes**: Different button sizes should be available, such as small, medium, and large.
- **Disabled State**: The component should handle a disabled state for buttons.
- **Events**: It should support common button events like `onClick`.

**Design Guidelines:**

The `Button` component's design should align with our project's UI/UX guidelines, maintaining consistency with the established color schemes. Please refer to the Figma design for visual guidelines: [Figma Design](https://www.figma.com/file/WgmdhEtnF0C90qPuvvm3OS/AbegHelp-(Copy)?type=design&node-id=316-652&mode=design&t=cnaEw6puMBiT7sqE-4).

**Implementation Details:**

To fulfill this request, you should:

1. Implement the `Button` component using `forwardRef`.
2. Create a TypeScript file named `button.tsx` in the `components/primitives/Button` directory.
3. Develop the `Button` component with support for different variants, sizes, and states as specified.
4. Implement the necessary event handling (e.g., `onClick`) for the button.
5. Ensure the component includes a spread props functionality to allow other props.

**Steps to Take:**

1. Implement the `Button` component using `forwardRef`.
2. Create the `button.tsx` file in the `components/primitives/Button` directory.
3. Develop the `Button` component with the specified design guidelines and features.
4. Ensure the component's behavior adheres to the requirements for variants, sizes, and events.
5. Add a spread props functionality to the `Button` component to enable the use of other props.

Here's a basic code snippet to get you started:

```jsx
import React, { forwardRef } from 'react';

interface ButtonProps {
  variant: 'primary' | 'secondary' | 'danger';
  size: 'sm' | 'base' | 'lg';
  disabled?: boolean;
  onClick?: () => void;
  label: string;
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(({ variant, size, disabled, onClick, label, ...props }, ref) => {
  return (
    <button ref={ref} className={classNames} onClick={onClick} disabled={disabled} {...props}>
      {label}
    </button>
  );
});

Button.displayName = 'Button';

export default Button;
```

**Expected Outcome:**

The expected outcome is the successful implementation of the `Button` component using `forwardRef`, along with the addition of the spread props functionality. This implementation will provide a versatile and reusable button component for various user interactions within our project.

**Notte:**

If you have any questions or need further details, please feel free to ask.

**Comment by Danieljs-codes** [comment]
I think instead of bloating it with props the interface can extend ComponentProps<"button"> so it accepts everything a button can but extend it with variant and size

**Comment by jemmycodes** [comment]
.take
