### ISSUE TITLE
Feature: Add Typography Component Group with `@tailwindcss/typography` Integration

### ISSUE THREAD

**Issue by babblebey** [abeg-help/frontend#108]
## Issue Type

- [ ] Bug Report
- [x] Feature Request
- [x] Enhancement
- [ ] Other (Please specify)

## Description

Add a Typography component group, consisting of `Title`, and a `TypographyWrapper` component, to the `primitives` directory within the project structure.

**Details:**

**Typography Component Group:**

This component group is designed to leverage the `@tailwindcss/typography` plugin, enhancing the typographic capabilities of our project. The group will consist of the following components:

1. `Title` (new component)
2. `TypographyWrapper` (new component)

**Configuration:**

**@tailwindcss/typography Plugin Integration:**

To achieve seamless integration with the `@tailwindcss/typography` plugin, we will configure it appropriately within the `tailwind.config.js` file. This will provide access to the `prose` utility class.

**TypographyWrapper Component:**

The `TypographyWrapper` component will serve as a wrapper for the `Title` and `Text` (future implementation) components. It will allow developers to apply typographic defaults to raw HTML content rendered from Markdown, improving readability and aesthetics. The `TypographyWrapper` component will accept the following props:

- `className` (optional): This prop enables the application of additional CSS classes if needed.

- `size` (optional): It provides control over the typography size by applying dynamically generated classes based on the provided `size` prop value. For instance, if `size` is set to "sm," the class `prose-sm` will be applied, resulting in a smaller font size and line height. Default size is "md."

- `...props`: The `TypographyWrapper` component should also accept and spread any other props to allow developers to use additional attributes on the wrapper element.

**Title Component:**

The `Title` component is responsible for rendering titles with semantic HTML elements. It accepts the following props through the provided `TitleProps` interface:

- `children`: Allows for the inclusion of content within the `Title` component. It accepts React nodes.

- `level` (optional, default: 1): Specifies the HTML title element (e.g., `<h1>`, `<h2>`) to be rendered. This prop provides semantic structuring options. The default `level` is 1 (rendering `<h1>`). The component will be configured to have a medium font weight by default, enhancing visual appeal.

**Outcome:**

The integration of the Typography component group, alongside the @tailwindcss/typography plugin, will enhance the typographic experience of our project. The added `Title` component ensures semantic and accessible structuring of titles, while the default medium font weight configuration promotes a consistent and visually appealing design.

**How to Implement:**

The implementation of the Typography component group should involve the creation of the `Title`, and `TypographyWrapper` components within their respective files in the `primitives` directory. Additionally, the configuration of the @tailwindcss/typography plugin should be performed in the `tailwind.config.js` file.

Developers should take into consideration the semantic HTML structure and utilize the `level` prop for the `Title` component.

**Resources:**

- For reference, please look at the `@tailwindcss/typography` plugin doc available [here](https://tailwindcss.com/docs/typography-plugin).
- You can be intentional and steal some code from the implementation [here](https://github.com/open-sauced/app/pull/1438) 😉 

**Note:**

If you have any questions, require further details, or need assistance with the implementation, please feel free to reach out.

**Comment by Danieljs-codes** [comment]
What the use case for Tailwind Typography
