### ISSUE TITLE
Feature: Implement `Signup` process

### ISSUE THREAD

**Issue by 289Volts** [abeg-help/frontend#120]
## Issue Type

- [ ] Bug Report
- [X] Feature Request
- [ ] Enhancement
- [ ] Other (Please specify)

## Description

You are to create a signup page and email verification feedback page for new users. 

## Requirements

- The page will need to be responsive on **mobile**, **tablet** and **desktop**. Ensure that colors used in the design are what you use. If the color you need is not in the `tailwind.config` file, add it following the existing pattern in the file.
- Incorporate the use of the custom `Input` component that was created. 

The design for this issue can be found [here](https://www.figma.com/file/dmkLquN3MVfcc5HRtg4pHV/AbegHelp?type=design&node-id=0-1&mode=design&t=OObrmH5zMR1OMlgb-0).

## Steps to take

- Create a `signup` folder inside the `pages` directory. 
- In the `signup` folder, create your `index.tsx` file which will serve as the signup page (`/signup`)
- Also create a `verfication.tsx` file which will serve as the verification page (`/signup/verification`)

```
pages ------
     signup------
           index.tsx    
           verification.tsx
``` 
- Check the [api documentation](https://documenter.getpostman.com/view/8405380/2s9YXk21DZ) and get the `signup` or `register` endpoint. Send a `POST` request to the endpoint with the form input values as the payload.

## Additional Information

Here are screenshots of the pages.
<img src="https://github.com/abeg-help/frontend/assets/66239216/b723de5a-677c-4d58-ab2d-663a47316e99"  width="30%" height="30%">
<img src="https://github.com/abeg-help/frontend/assets/66239216/d06b2f0a-45a6-476e-9d05-daee1ae8dc4f"  width="30%" height="30%">
<img src="https://github.com/abeg-help/frontend/assets/66239216/bc2e992c-cfe2-456b-95ec-fe59a8102aca"  width="60%" height="30%">
<img src="https://github.com/abeg-help/frontend/assets/66239216/9aaa0e1b-141a-48bc-95f9-47541ad67d5e"  width="60%" height="30%">

## Would you like to contribute to fixing this issue?

- [ ] Yes
- [ ] No

**Note:** Please make sure to follow the project's code of conduct and contribution guidelines when creating an issue. Thank you for contributing to our open-source project! 

If you have any questions or need further details, please feel free to ask.

**Comment by Judge-Paul** [comment]
.take
