### ISSUE TITLE
Feature: Implement `Reset password` process

### ISSUE THREAD

**Issue by 289Volts** [abeg-help/frontend#122]
## Issue Type

- [ ] Bug Report
- [X] Feature Request
- [ ] Enhancement
- [ ] Other (Please specify)

## Description

You are to create a reset password page and confirmation feedback page. 

## Requirements

- The page will need to be responsive on **mobile**, **tablet** and **desktop**. Ensure that colors used in the design are what you use. If the color you need is not in the `tailwind.config` file, add it following the existing pattern in the file.
- Incorporate the use of the custom `Input` component that was created. 

The design for this issue can be found [here](https://www.figma.com/file/dmkLquN3MVfcc5HRtg4pHV/AbegHelp?type=design&node-id=0-1&mode=design&t=OObrmH5zMR1OMlgb-0).

## Steps to take

- Create a `reset-password` folder inside the `pages` directory. 
- In the `reset-password` folder, create your `index.tsx` file which will serve as the signup page (`/reset-password`)
- Also create a `confirmation.tsx` file which will serve as the verification page (`/reset-password/confirmation`)

```
pages ------
     reset-password------
           index.tsx    
           confirmation.tsx
``` 
- Check the [api documentation](https://documenter.getpostman.com/view/8405380/2s9YXk21DZ) and get the `reset-password` endpoint. Send a `POST` request to the endpoint with the form input values as the payload.

## Additional Information

Here are screenshots of the pages.
<img src="https://github.com/abeg-help/frontend/assets/66239216/4bb27834-340c-47bd-b659-e5ed7f2e563b"  width="30%" height="30%">
<img src="https://github.com/abeg-help/frontend/assets/66239216/8d2fc1f3-e2ab-4030-b509-dacbc6607fe0"  width="30%" height="30%">
<img src="https://github.com/abeg-help/frontend/assets/66239216/d6c67889-8fb2-4f2e-bdd5-a38081930ee3"  width="60%" height="30%">
<img src="https://github.com/abeg-help/frontend/assets/66239216/937ea6ba-e40d-48f3-b98a-67bf239ba9be"  width="60%" height="30%">

## Would you like to contribute to fixing this issue?

- [ ] Yes
- [ ] No

**Note:** Please make sure to follow the project's code of conduct and contribution guidelines when creating an issue. Thank you for contributing to our open-source project! 

If you have any questions or need further details, please feel free to ask.

**Comment by Lawrenceku** [comment]
.take

**Comment by kelechukwu1** [comment]
.take
