### ISSUE TITLE
Integrate `React Query` for Improved HTTP Request Handling

### ISSUE THREAD

**Issue by babblebey** [abeg-help/frontend#123]
## Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Enhancement
- [ ] Other (Please specify)

## Description

We aim to enhance the project's data fetching and state management capabilities by integrating [React Query](https://react-query.tanstack.com/), a library that simplifies data fetching, caching, and state management.

1. Install React Query:
    - Add React Query to the project dependencies.
2. Configure React Query Setup:
    - Set up a global React Query provider in your application.
    - Configure the default options for queries and mutations.
3. Create a Custom Hook for HTTP Requests:
    - Design a custom hook to encapsulate HTTP requests using React Query.
4. Integrate in Components:
    - Modify existing components to use the newly created custom hook for data fetching.

### Resources:

- [React Query Documentation](https://react-query.tanstack.com/)

**Comment by ryan-zayne** [comment]
.take
