### ISSUE TITLE
Typo errors and mobile responsiveness 

### ISSUE THREAD

**Issue by Idighekere** [abeg-help/frontend#205]
## Issue Type

- [ ] Enhancement

## Description

Typo errors and mobile responsiveness

## Details

Some words have been misspelt (Freequently) and (Sponsoship). 
There's a white space at the right of the page on mobile

![Screenshot_20240308-224357](https://github.com/abeg-help/frontend/assets/101113870/b3385d11-3a71-44e0-bcb2-4db8f9b3bd54)
![Screenshot_20240308-224336](https://github.com/abeg-help/frontend/assets/101113870/b7529123-49f3-40d2-b2ce-b55485374389)
![Screenshot_20240308-223855](https://github.com/abeg-help/frontend/assets/101113870/74a5c21d-9395-4c76-bc09-652ec423c120)

**Comment by 1finedev** [comment]
would you like to take the issue @Idighekere

**Comment by Idighekere** [comment]
It has been resolved
