### ISSUE TITLE
Fix typo and use the correct router

### ISSUE THREAD

**Issue by 1finedev** [abeg-help/frontend#279]
## Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Enhancement
- [ ] Other (Please specify)

## Description

There is a typo in the `callApi` file inside of `/lib/helpers/callApi.ts` on `line 66`

Help change the *may* to *many*

also there is an inconsistency in the usage of redirection in the `/store/useSession` store  on `line 64` where the browser history is being manually modified with `window.location.replace("/signin?unauthorized=true");`, kindly help change the logic to also mimic what was used in `line 77` of the callApi file which uses the next router instead

**Comment by jemmycodes** [comment]
.take

**Comment by ryan-zayne** [comment]
Merged!
