### ISSUE TITLE
Move `ISSUE_TEMPLATE.md` to the `.github` Folder

### ISSUE THREAD

**Issue by babblebey** [abeg-help/frontend#72]
## Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Enhancement
- [ ] Other (Please specify)

## Description

We have an `ISSUE_TEMPLATE.md` file in the root directory of our repository, and we would like to improve our repository's organization by moving it to the `.github` folder. This will make our project structure cleaner and ensure that our issue template is consistently applied across the repository.

### Proposed Change

We propose moving the `ISSUE_TEMPLATE.md` file from the root directory to the `.github` folder.

### Reasoning

- Cleaner Repository Structure: Moving the `ISSUE_TEMPLATE.md` file to the `.github` folder will enhance the cleanliness of our repository structure and make it easier to find relevant files.
- Consistency: Placing the issue template in the `.github` folder ensures that it's consistently applied to issues and provides a central location for related GitHub configuration files.

### Steps to Take

- Move the `ISSUE_TEMPLATE.md` file from the root directory to the `.github` folder.
- Update any references or links in the repository that point to the issue template to reflect its new location.

### Expected Outcome

We expect that the `ISSUE_TEMPLATE.md`  file will be successfully moved to the `.github` folder. This will improve our repository's organization and maintain consistency across our GitHub repository.

## Would you like to contribute to fixing this issue?

- [ ] Yes
- [x] No

**Comment by Judge-Paul** [comment]
Can you assign me this
