### ISSUE TITLE
Remove `.vscode` Folder and Update `.gitignore`

### ISSUE THREAD

**Issue by babblebey** [abeg-help/frontend#73]
## Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Enhancement
- [ ] Other (Please specify)

## Description

Currently, we have a `.vscode` folder in the root directory of our repository. This folder contains Visual Studio Code-specific configuration files. To maintain a cleaner and more consistent repository structure, we would like to remove the `.vscode` folder from the root directory and ensure that it's properly ignored by adding a rule to our `.gitignore` file.

## Additional Information

**Proposed Changes**

1. Delete the `.vscode` folder from the repository's root directory.
2. Update our `.gitignore` file to include a rule that ensures the `.vscode` folder and its contents are ignored.

**Reasoning**

- **Cleaner Repository Structure**: Removing the `.vscode` folder from the root directory helps maintain a cleaner repository structure by eliminating unnecessary IDE-specific configuration files.
- **Consistency**: Ensuring that the `.vscode` folder is ignored via the `.gitignore` file is a best practice to prevent inadvertently committing these files to our repository.

**Steps to Take**

1. Delete the `.vscode` folder from the root directory.
2. Open the `.gitignore` file and add a rule to ignore the `.vscode/` folder and its contents. The rule should look like this: `.vscode/`

**Expected Outcome**

The `.vscode` folder will be successfully removed from the root directory of our repository, and the `.gitignore` file will be updated to ensure that it's ignored.

## Would you like to contribute to fixing this issue?

- [ ] Yes
- [x] No

**Comment by Toyin5** [comment]
.take

**Comment by Klin-Coders** [comment]
After reconsideration, we decided it would serve us best to leave it in the repo.
