### ISSUE TITLE
I Want to Add Docker Images for repo 

### ISSUE THREAD

**Issue by Adidem23** [abeg-help/frontend#77]
# Issue Template

## Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Enhancement
- [ ] Other (Please specify)

## Description
I want to add and deploy our project to docker . I will add one Dockerfile and .dockerignore and build the whole project on docker . Final Outcome of this procedure will be one command by which we can setup our whole code in another system without having code files 

## Details
- Add DockerFile
- Build DockerImage
- Give the final docker image for testing 
- Give file for running docker image

## Expected Behavior (For Bug Reports)
Run the project on other machines without having any initial setup . Make the accessible to everyone 

## Would you like to contribute to fixing this issue?

- [x] Yes
- [ ] No

**Comment by Klin-Coders** [comment]
Cheers, we would love that. kindly take a look at the backend repo and pick up or create similar issues

[https://github.com/abeg-help/backend/pull/46](Backend Repo)

**Comment by Adidem23** [comment]
Thank You !!

**Comment by babblebey** [comment]
We will closing this maybe temporarily for now, we surely will be considering this later on in the project.
