### ISSUE TITLE
Add Boilerplate Pages for Login and Register

### ISSUE THREAD

**Issue by babblebey** [abeg-help/frontend#86]
## Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Enhancement
- [ ] Other (Please specify)

## Description

We need to enhance your favourite project by adding boilerplate pages for login and register in the `pages` directory. These pages will serve as the foundation for our authentication system. We have found a suitable resource that provides a login card design that we'd like to use as a starting point. 

## Additional Information

**Resource**

- The design and layout for these pages should closely follow the example provided in the [Tailwind CSS Login Card](https://tailwindcomponents.com/component/tailwind-css-login-card) resource.

**Proposed Changes**

- Two pages should be created, `login.tsx` and `register.tsx`, directly in the `pages` directory.
- These pages doesn't need to be broken down into components. The implementation should be written directly within these files.
- The content and layout of these pages should be based on the design provided by the Tailwind CSS Login Card resource.

**Steps to Take**

1. Create a new file `login.tsx` in the `pages` directory.
2. Implement the login page based on the design from the provided resource.
3. Create a new file `register.tsx` in the `pages` directory.
4. Implement the register page based on the design from the provided resource.
5. Ensure that these pages somewhat replicates the design and functionality specified in the Tailwind CSS Login Card.

**Expected Outcome**

Upon completion, we will have two new pages, `login.tsx` and `register.tsx`, in the `pages` directory. These pages will serve as a boilerplate for our login and register functionality, following the design and layout from the provided resource.

**Working on this?**

If you have any questions or need further guidance, please don't hesitate to ask. This issue will help track the progress of this task.

**Comment by jemmycodes** [comment]
. take

**Comment by Kofi-eo** [comment]
.take

**Comment by Lawrenceku** [comment]
. take

**Comment by babblebey** [comment]
Closed in #88
